#!/bin/bash

# Cloudflared 自动管理脚本
# 功能：自动重启 + 域名变更时自动同步到 Git

set -e

# ==================== 配置区 ====================
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLOUDFLARED_LOG="${PROJECT_DIR}/cloudflared.log"
CLOUDFLARED_PID_FILE="${PROJECT_DIR}/cloudflared.pid"
DOMAIN_CONFIG_FILE="${PROJECT_DIR}/.cloudflared-domain"

# 自动检测当前 Git 分支，如果不在 git 仓库中则使用 main
if git rev-parse --is-inside-work-tree &>/dev/null 2>&1; then
    GIT_BRANCH="${CLOUDFLARED_GIT_BRANCH:-$(git branch --show-current 2>/dev/null || echo main)}"
else
    GIT_BRANCH="${CLOUDFLARED_GIT_BRANCH:-main}"
fi

GIT_COMMIT_MESSAGE_PREFIX="${CLOUDFLARED_GIT_COMMIT_MSG:-chore: update cloudflared domain}"
LOCAL_PORT="${CLOUDFLARED_LOCAL_PORT:-80}"
CHECK_INTERVAL="${CLOUDFLARED_CHECK_INTERVAL:-10}"
MAX_RESTART_DELAY="${CLOUDFLARED_MAX_RESTART_DELAY:-30}"
# ===============================================

# 颜色输出
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $(date '+%Y-%m-%d %H:%M:%S') $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $(date '+%Y-%m-%d %H:%M:%S') $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $(date '+%Y-%m-%d %H:%M:%S') $1"
}

log_debug() {
    echo -e "${BLUE}[DEBUG]${NC} $(date '+%Y-%m-%d %H:%M:%S') $1"
}

# 检查 cloudflared 是否已安装
check_cloudflared() {
    if ! command -v cloudflared &> /dev/null; then
        log_error "cloudflared 未安装，请先安装："
        echo "  macOS: brew install cloudflared"
        echo "  Linux: 参考 https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/"
        exit 1
    fi
}

# 获取当前运行的 cloudflared URL
get_current_url() {
    if [ -f "$CLOUDFLARED_PID_FILE" ]; then
        local pid=$(cat "$CLOUDFLARED_PID_FILE" 2>/dev/null)
        if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
            # 从日志中获取最新的 URL
            if [ -f "$CLOUDFLARED_LOG" ]; then
                grep -oP 'https://[a-zA-Z0-9.-]+\.trycloudflare\.com' "$CLOUDFLARED_LOG" | tail -1
            fi
        fi
    fi
}

# 保存域名到配置文件
save_domain() {
    local domain=$1
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    
    cat > "$DOMAIN_CONFIG_FILE" << EOF
# Cloudflared 域名配置 - 自动生成
# 最后更新: $timestamp
DOMAIN=$domain
UPDATED_AT=$timestamp
EOF
    
    log_info "域名已保存到 $DOMAIN_CONFIG_FILE"
}

# 读取上次保存的域名
get_saved_domain() {
    if [ -f "$DOMAIN_CONFIG_FILE" ]; then
        grep "^DOMAIN=" "$DOMAIN_CONFIG_FILE" | cut -d'=' -f2
    fi
}

# 检查 Git 配置
check_git_config() {
    if ! git rev-parse --is-inside-work-tree &>/dev/null; then
        return 1
    fi
    
    # 检查是否配置了用户信息
    local user_name=$(git config user.name 2>/dev/null)
    local user_email=$(git config user.email 2>/dev/null)
    
    if [ -z "$user_name" ] || [ -z "$user_email" ]; then
        log_warn "Git 用户信息未配置，将跳过自动提交"
        log_info "运行以下命令配置 Git："
        echo "  git config user.name 'Your Name'"
        echo "  git config user.email 'your@email.com'"
        return 1
    fi
    
    # 检查是否有远程仓库和推送权限
    if ! git remote get-url origin &>/dev/null; then
        log_warn "未配置 Git 远程仓库，将跳过自动推送"
        return 2
    fi
    
    return 0
}

# 同步域名到 Git
sync_domain_to_git() {
    local domain=$1
    
    # 检查 Git 配置
    check_git_config
    local git_status=$?
    
    if [ $git_status -eq 1 ]; then
        log_debug "不在 Git 仓库中，仅保存本地配置"
        save_domain "$domain"
        update_env_file "$domain"
        return
    fi
    
    # 检查是否有变更
    local saved_domain=$(get_saved_domain)
    if [ "$saved_domain" = "$domain" ]; then
        log_debug "域名未变更，跳过 Git 同步"
        return
    fi
    
    log_info "检测到域名变更: ${saved_domain:-无} -> $domain"
    log_info "正在同步到 Git..."
    
    # 保存域名到配置文件
    save_domain "$domain"
    
    # 更新 .env 文件（如果存在）
    update_env_file "$domain"
    
    # Git 操作
    cd "$PROJECT_DIR"
    
    # 添加文件
    git add "$DOMAIN_CONFIG_FILE" 2>/dev/null || true
    git add ".env" 2>/dev/null || true
    
    # 检查是否有变更需要提交
    if git diff --cached --quiet; then
        log_debug "没有变更需要提交"
        return
    fi
    
    # 提交
    if git commit -m "${GIT_COMMIT_MESSAGE_PREFIX}

域名: $domain
时间: $(date '+%Y-%m-%d %H:%M:%S')

Auto-generated by cloudflared-manager.sh" 2>/dev/null; then
        log_info "Git 提交成功"
    else
        log_warn "Git commit 失败"
        return
    fi
    
    # 推送到远程仓库（仅在 Git 配置完整时）
    if [ $git_status -eq 0 ]; then
        log_info "正在推送到 origin/$GIT_BRANCH..."
        local push_output
        if push_output=$(git push origin "$GIT_BRANCH" 2>&1); then
            log_info "Git 推送成功: $domain"
        else
            log_warn "Git push 失败，域名已本地保存"
            log_warn "推送输出:"
            echo "$push_output" | while read line; do
                log_warn "  $line"
            done
            log_warn ""
            log_warn "请检查："
            log_warn "  1. 远程仓库地址: git remote -v"
            log_warn "  2. 当前分支: git branch"
            log_warn "  3. SSH 认证: ssh -T git@github.com"
            log_warn "  4. 手动推送测试: git push origin $GIT_BRANCH"
        fi
    else
        log_info "域名已本地保存，跳过远程推送"
    fi
}

# 更新 .env 文件中的域名
update_env_file() {
    local domain=$1
    local env_file="${PROJECT_DIR}/.env"
    
    if [ ! -f "$env_file" ]; then
        log_debug ".env 文件不存在，跳过更新"
        return
    fi
    
    # 更新或添加 CLOUDFLARE_DOMAIN 变量
    if grep -q "^CLOUDFLARE_DOMAIN=" "$env_file"; then
        sed -i.bak "s|^CLOUDFLARE_DOMAIN=.*|CLOUDFLARE_DOMAIN=$domain|" "$env_file"
        rm -f "${env_file}.bak"
    else
        echo "" >> "$env_file"
        echo "# Cloudflared 临时域名" >> "$env_file"
        echo "CLOUDFLARE_DOMAIN=$domain" >> "$env_file"
    fi
    
    log_info ".env 文件已更新"
}

# 启动 cloudflared
start_cloudflared() {
    log_info "启动 cloudflared tunnel -> http://localhost:${LOCAL_PORT}"
    
    # 清理旧的日志和 PID 文件
    rm -f "$CLOUDFLARED_LOG" "$CLOUDFLARED_PID_FILE"
    
    # 启动 cloudflared 后台进程
    cloudflared tunnel --url "http://localhost:${LOCAL_PORT}" 2>&1 | tee "$CLOUDFLARED_LOG" &
    local pid=$!
    
    echo "$pid" > "$CLOUDFLARED_PID_FILE"
    log_info "cloudflared 已启动 (PID: $pid)"
    
    # 等待 URL 出现
    local wait_count=0
    local max_wait=30
    
    while [ $wait_count -lt $max_wait ]; do
        sleep 1
        local url=$(get_current_url)
        if [ -n "$url" ]; then
            log_info "Tunnel URL: $url"
            
            # 同步到 Git
            sync_domain_to_git "$url"
            
            return 0
        fi
        wait_count=$((wait_count + 1))
    done
    
    log_error "等待 cloudflared URL 超时"
    return 1
}

# 停止 cloudflared
stop_cloudflared() {
    if [ -f "$CLOUDFLARED_PID_FILE" ]; then
        local pid=$(cat "$CLOUDFLARED_PID_FILE")
        if kill -0 "$pid" 2>/dev/null; then
            log_info "停止 cloudflared (PID: $pid)..."
            kill "$pid" 2>/dev/null || true
            sleep 2
            # 确保进程已停止
            if kill -0 "$pid" 2>/dev/null; then
                kill -9 "$pid" 2>/dev/null || true
            fi
            log_info "cloudflared 已停止"
        fi
        rm -f "$CLOUDFLARED_PID_FILE"
    else
        log_warn "未找到 cloudflared PID 文件"
    fi
}

# 检查 cloudflared 是否运行
is_running() {
    if [ -f "$CLOUDFLARED_PID_FILE" ]; then
        local pid=$(cat "$CLOUDFLARED_PID_FILE")
        if kill -0 "$pid" 2>/dev/null; then
            return 0
        fi
    fi
    return 1
}

# 监控 cloudflared 状态并自动重启
monitor() {
    log_info "开始监控 cloudflared (检查间隔: ${CHECK_INTERVAL}s)"
    
    local restart_count=0
    local last_restart_time=0
    
    while true; do
        if ! is_running; then
            local current_time=$(date +%s)
            local time_since_last_restart=$((current_time - last_restart_time))
            
            # 防止频繁重启（最小间隔 5 秒）
            if [ $time_since_last_restart -lt 5 ]; then
                local wait_time=$((5 - time_since_last_restart))
                log_warn "重启过于频繁，等待 ${wait_time}s..."
                sleep $wait_time
            fi
            
            restart_count=$((restart_count + 1))
            last_restart_time=$(date +%s)
            
            log_warn "cloudflared 已断开，正在自动重启 (第 ${restart_count} 次)..."
            
            # 随机延迟避免同时重启（如果多个实例）
            local random_delay=$((RANDOM % MAX_RESTART_DELAY + 1))
            log_debug "延迟 ${random_delay}s 后重启..."
            sleep $random_delay
            
            start_cloudflared
        else
            # 定期检查日志中是否有新的 URL（可选）
            local current_url=$(get_current_url)
            if [ -n "$current_url" ]; then
                local saved_domain=$(get_saved_domain)
                if [ "$saved_domain" != "$current_url" ]; then
                    log_info "检测到域名变更，同步到 Git..."
                    sync_domain_to_git "$current_url"
                fi
            fi
        fi
        
        sleep "$CHECK_INTERVAL"
    done
}

# 显示状态
status() {
    if is_running; then
        local pid=$(cat "$CLOUDFLARED_PID_FILE")
        local url=$(get_current_url)
        echo -e "${GREEN}● cloudflared 运行中${NC}"
        echo "  PID: $pid"
        echo "  URL: ${url:-获取中...}"
        
        if [ -f "$DOMAIN_CONFIG_FILE" ]; then
            local saved=$(get_saved_domain)
            echo "  已同步域名: ${saved:-无}"
        fi
    else
        echo -e "${RED}● cloudflared 未运行${NC}"
    fi
}

# 显示日志
logs() {
    if [ -f "$CLOUDFLARED_LOG" ]; then
        tail -f "$CLOUDFLARED_LOG"
    else
        log_warn "日志文件不存在"
    fi
}

# ==================== 主程序 ====================

check_cloudflared

case "${1:-start}" in
    start)
        if is_running; then
            log_warn "cloudflared 已在运行"
            status
        else
            start_cloudflared
            log_info "使用 'bash cloudflared-manager.sh monitor' 启动自动监控模式"
        fi
        ;;
    
    stop)
        stop_cloudflared
        ;;
    
    restart)
        stop_cloudflared
        sleep 2
        start_cloudflared
        ;;
    
    monitor)
        log_info "启动 cloudflared 自动监控模式"
        log_info "按 Ctrl+C 停止监控"
        echo ""
        
        # 先启动 cloudflared（如果未运行）
        if ! is_running; then
            start_cloudflared
        fi
        
        # 开始监控
        monitor
        ;;
    
    status)
        status
        ;;
    
    logs)
        logs
        ;;
    
    *)
        echo "用法: bash cloudflared-manager.sh {start|stop|restart|monitor|status|logs}"
        echo ""
        echo "命令:"
        echo "  start   - 启动 cloudflared tunnel"
        echo "  stop    - 停止 cloudflared tunnel"
        echo "  restart - 重启 cloudflared tunnel"
        echo "  monitor - 启动监控模式（自动重启 + Git 同步）"
        echo "  status  - 查看运行状态"
        echo "  logs    - 查看日志"
        echo ""
        echo "环境变量:"
        echo "  CLOUDFLARED_LOCAL_PORT        - 本地端口 (默认: 80)"
        echo "  CLOUDFLARED_CHECK_INTERVAL    - 检查间隔秒数 (默认: 10)"
        echo "  CLOUDFLARED_GIT_BRANCH        - Git 分支 (默认: main)"
        echo "  CLOUDFLARED_GIT_COMMIT_MSG    - Git 提交消息前缀"
        echo "  CLOUDFLARED_MAX_RESTART_DELAY - 最大重启延迟秒数 (默认: 30)"
        ;;
esac
